### ISSUE TITLE
Add a proper Navbar

### ISSUE THREAD

**Issue by yolk23** [LismaxB/Ceylon-Public-Transit#41]
**Description:**
The current navbar is just a title. It's okay but maybe we can add some user interactivity or if not may be we can just add a simple styling for better UX 
![image](https://github.com/user-attachments/assets/a0191831-ee42-4f99-a83f-e173dc20eceb)

**Comment by LismaxB** [comment]
@yolk23 Yes, of course! Feel free to make a PR for this. Would you like me to assign you to the task?

**Comment by yolk23** [comment]
Hey, @LismaxB you're welcome bro. My bad wasn't able to reply was out the whole day thanks!

**Comment by LismaxB** [comment]
@yolk23 No worries, feel free to go through the project and create issues/PRs.
